id = "zed-reef-extension"
name = "Zed Reef Extension"
version = "0.0.1"
schema_version = 1
authors = ["Malachi Mackie <malachi@mackie.co.nz>"]
description = "Zed Language extension for Reef programming language"
repository = "https://github.com/MalachiMackie/zed-reef-extension"

[grammars.reef]
repository = "https://github.com/MalachiMackie/tree-sitter-reef"
rev = "865d66dc12ccd4a8fed29426f639b80ab53cb852"
