id = "zed-reef-extension"
name = "Zed Reef Extension"
version = "0.0.1"
schema_version = 1
authors = ["Malachi Mackie <malachi@mackie.co.nz>"]
description = "Zed Language extension for Reef programming language"
repository = "https://github.com/MalachiMackie/zed-reef-extension"

[grammars.reef]
repository = "https://github.com/MalachiMackie/tree-sitter-reef"
rev = "26d301ab18398379a8468f252a0c47ab22750614"
